### ISSUE TITLE
Error after selecting broken character

### ISSUE THREAD

**Issue by GlavenusGuy** [ricochhet/Erupe#28]
So I'm trying to use the Erupe version of Frontier.  I've been able to turn on the server, disable GameGuard, enter my username and password into the launcher, and select the broken character.  However after that, I keep getting the below error.  I've been troubleshooting with someone on Twitter for a day and change now, and nothing we've tried has worked.  I tried reinstalling all the files, restarting my laptop, changing my region and timezone to both Japan and Taiwan, updating Python to 3.9.6, and clearing my Internet Explorer cache, and still nothing has worked.  Any help on this would be greatly appreciated!
<img width="193" alt="Frontier Error" src="https://user-images.githubusercontent.com/98071811/150267893-4803c679-63f2-4642-b1f9-cf4aea0e6ef2.PNG">

**Comment by Stefan240** [comment]
Do you by any chance have High Grade Assets enabled?
You can find the option when you launch the launcher and before logging in hit "Config" there you will find a checkbox to either enable (checkbox checked) or disable (checkbox unchecked) the High Grade Assets. The Patcher script provided in the repo as of yet still does not support HG-Assets, so that may be your problem. 

Also I did not test if the script even works on python 3.9 can you give me feedback if it still works with python 3.9, please?

**Comment by GlavenusGuy** [comment]
> 

Looks like it was High Grade Edition!  Thanks for your help!

**Comment by DaraAmadyura** [comment]
> Do you by any chance have High Grade Assets enabled? You can find the option when you launch the launcher and before logging in hit "Config" there you will find a checkbox to either enable (checkbox checked) or disable (checkbox unchecked) the High Grade Assets. The Patcher script provided in the repo as of yet still does not support HG-Assets, so that may be your problem.
> 
> Also I did not test if the script even works on python 3.9 can you give me feedback if it still works with python 3.9, please?

I'm not sure if you'll see this, but I managed to get my setup to work with Python 3.9.6 and the latest version of Frida. Haven't tested other versions of 3.9, but I know for sure versions of 3.10 caused some issues with people
