### ISSUE TITLE
I don't know how to log in from the client

### ISSUE THREAD

**Issue by AzDj** [ricochhet/Erupe#31]
Hello, I have successfully run the service, but how do I log in from the client

**Comment by AzDj** [comment]
![image](https://user-images.githubusercontent.com/35040319/150629148-68efe8e4-5425-41be-b368-ca21a724b6b0.png)
postgresql version: 13
I tried to manually create the user in the database but still got it error

**Comment by Stefan240** [comment]
normally you should be able to just type in anything really. If an account does not exist yet, with that name the server will create one. 

> ![image](https://user-images.githubusercontent.com/35040319/150629148-68efe8e4-5425-41be-b368-ca21a724b6b0.png) postgresql version: 13 I tried to manually create the user in the database but still got it error

Since you played around with database already it might be a good idea to start with a fresh database. Shut off the server, 
open up pgadmin4 and delete the erupe database and create a new one. 

Then go into your Erupe Server folder and migrate the databases: (run this command in either powershell or cmd)
`migrate -database postgres://postgres:password@localhost:5432/erupe?sslmode=disable -path migrations up`

Then make sure to delete the Internet Explorer Cache as stated here: https://github.com/ricochhet/Erupe/blob/master/docs/Troubleshooting.md#general-tips 

After that start the server again and see if typing in anything will work. If not it would be very helpful to have a server-log. You can copy the output in the shell by highlighting stuff with the mouse and right-click.

**Comment by AzDj** [comment]
> normally you should be able to just type in anything really. If an account does not exist yet, with that name the server will create one.
> 
> > ![image](https://user-images.githubusercontent.com/35040319/150629148-68efe8e4-5425-41be-b368-ca21a724b6b0.png) postgresql version: 13 I tried to manually create the user in the database but still got it error
> 
> Since you played around with database already it might be a good idea to start with a fresh database. Shut off the server, open up pgadmin4 and delete the erupe database and create a new one.
> 
> Then go into your Erupe Server folder and migrate the databases: (run this command in either powershell or cmd) `migrate -database postgres://postgres:password@localhost:5432/erupe?sslmode=disable -path migrations up`
> 
> Then make sure to delete the Internet Explorer Cache as stated here: https://github.com/ricochhet/Erupe/blob/master/docs/Troubleshooting.md#general-tips
> 
> After that start the server again and see if typing in anything will work. If not it would be very helpful to have a server-log. You can copy the output in the shell by highlighting stuff with the mouse and right-click.

Thanks for the reply, I confirmed that I have deleted the database and recreated the data.
But still getting the same error.

**Comment by AzDj** [comment]
I seem to have found a solution, because I ran the server in the cloud and did not release the required port to run. SO getting the error.
