### ISSUE TITLE
How can we play in High Grade mode

### ISSUE THREAD

**Issue by YufaWishui** [ricochhet/Erupe#37]

**Comment by Stefan240** [comment]
The fix to this problem seems allegedly fairly easy. It seems to boil down to this as I read in some comments around here: 
> You can try to modify all "mhfo.dll" to "mhfo-hd.dll" in no_gg_jp.py and enable "High Grade Edition" in config

I would have liked to add this to the repo, but I could not get that version working, for whatever reason it would crash for me. It might since I was running in a VM. Anyway if you get it working with this info please feel free to leave a Pull Request with the modified script, but be sure to not replace the old one but modify a copy named something like `no_gg_jp_hg.py` (maybe we can give it a more sensible name later)

**Comment by Stefan240** [comment]
@YufaWishui @MikeZTM fyi the high grade assets got fixed and merged with #59. Please download the new file an then you should be able to use High grade assets.
