### ISSUE TITLE
Infinite loading screen to Mezeporta

### ISSUE THREAD

**Issue by Ruinedquill183** [ricochhet/Erupe#42]
So, I have the game working up until after character creation
After I confirm the character and then confirm the weapon, I end up getting to the loading screen just before Mezeporta square
And it stays there, I've tried waiting 20+ minutes hoping it was just taking a while to load but nothing
I go to check on the erupe server cmd prompt and at the bottom I see
[]Recovered from panic pq: column "gcp" does not exist

What exactly do I do to fix this?

**Comment by Stefan240** [comment]
Can I get a full log please? All you get from the terminal after starting the server up to the point where you get that error. It might help me out to figure whats wrong. 

Any Error-Message from the client?

**Comment by Ruinedquill183** [comment]
![unknown-21](https://user-images.githubusercontent.com/98799309/152114598-a9f4d6c5-127e-49ff-9923-380f5871a183.png)
Here's a screenshot I took of it leading up to the issue, I could see about getting a better screenshot if needed

**Comment by Ruinedquill183** [comment]
> Can I get a full log please? All you get from the terminal after starting the server up to the point where you get that error. It might help me out to figure whats wrong.
> 
> Any Error-Message from the client?

As for the client no, it just stays in the loading screen as if it's trying to load but nothing else, no pop up saying there's an error just a loading screen

**Comment by Ruinedquill183** [comment]
![unknown-14](https://user-images.githubusercontent.com/98799309/152116013-79c4ed5a-0e83-4cb8-8a95-c99ebae8f8eb.png)
Ok here's one that goes from the VERY start of me getting the server going up until the no column: gcp thing

**Comment by K-Lemu** [comment]
I guess you are starting the server in a different erupe repository.
In this repository, there is no column for gcp in the character table, and `erupe\channelserver\` has a `session` but no file called `sys_session`.
So, the process has a panic because there is no table and file for it to call.

**Comment by Ruinedquill183** [comment]
> I guess you are starting the server in a different erupe repository. In this repository, there is no column for gcp in the character table, and `erupe\channelserver\` has a `session` but no file called `sys_session`. So, the process has a panic because there is no table and file for it to call.

Yknow, I'm not a tech savvy person but that does make sense
I was running into a similar issue where I downloaded newer files for frontier, trying to run those, and having it try to open stuff from the old files as opposed to the newly downloaded files (I fixed this issue and eventually got the game to run up until this current issue after replacing all the old files with the new ones)

I tried two different guides for getting everything set up (and figured I should keep the files separate just so it would be easier to clean up one if it somehow didn't work but the other one did)

**Comment by K-Lemu** [comment]
Yes, you're getting an error because you haven't created a database for that repository or done any migration.
If you want to play with the newly downloaded repository, create a new database with pgAdmin or psql (I also create multiple databases for testing, like erupe2).

Then do the migration in the new repository file.
If you have the migration file, you can use the same method, but if not, ask the person who created the repository.
Some people use csv files, binaries, or sql queries to create tables and columns.

If you don't create one database in one repository, you will get the same panic/crash if there is no data in the database that the repository references.
You cannot use multiple repositories for a single database.
Please make sure to create a dedicated database for it in postgreSQL.
